### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by endotermic** [myint/cppclean#130]
**Problem:**
File "...\cppclean\cpp\static_data.py", line 31, in print_warning
          for name in node.name.split(','):
AttributeError: 'NoneType' object has no attribute 'split'

**Possible solution:**
Additional check is needed.

**Temporary fix**
For now I use "try: except: pass" around FOR loop

**Comment by endotermic** [comment]
fixed in pull request #133

**Comment by endotermic** [comment]
if node.name is of type None then program abort happens.
I have no time to find out what triggers this issue but this little fix will not allow forbidden call to non existing method.

**Comment by bjaraujo** [comment]
I get a similar issue:

Traceback (most recent call last):
  File "/usr/local/bin/cppclean", line 145, in <module>
    sys.exit(main())
  File "/usr/local/bin/cppclean", line 138, in main
    quiet=args.quiet):
  File "/usr/local/lib/python2.7/dist-packages/cpp/static_data.py", line 117, in run
    _find_warnings(filename, lines, entire_ast, True) +
  File "/usr/local/lib/python2.7/dist-packages/cpp/static_data.py", line 64, in _find_warnings
    print_warning(node)
  File "/usr/local/lib/python2.7/dist-packages/cpp/static_data.py", line 31, in print_warning
    for name in node.name.split(','):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by bjaraujo** [comment]
No, this was using the latest released version.
Does cppclean have a GUI? 
I think cppclean is very good but it listed so many issues I need some way of editing the files quickly.

**Comment by bjaraujo** [comment]
I am still using cppclean. I rolled back because the master also gave me issues. Now I just use --exclude option to exclude the problematic file.

**Comment by endotermic** [comment]
Cppclean don't have GUI. It would be very good if you would report bug on
your issues.

вс, 4 нояб. 2018 г., 13:54 bjaraujo notifications@github.com:
