### ISSUE TITLE
Cppclean crashes on specific token (Got invalid token in ? @ 1710 token:@: u'SION_10_6\n@interface')

### ISSUE THREAD

**Issue by TheOnlyJoey** [myint/cppclean#50]
Hey all,

I am running Cppclean on 2 Ogre3d based projects and both segfault on a specific token:

Got invalid token in ? @ 1710 token:@: u'SION_10_6\n@interface'

This can be reproduced when running on a fresh download from the ogre website.
The file that causes this seems to be: OgrePrerequisites.h which gets called quite a lot.
Running just on that file seems to do no harm.

Thanks

Traceback (most recent call last):
  File "/usr/local/bin/cppclean", line 135, in <module>
    sys.exit(main())
  File "/usr/local/bin/cppclean", line 127, in main
    quiet=args.quiet)
  File "/usr/local/lib/python2.7/dist-packages/cpp/find_warnings.py", line 533, in run
    hunter.find_warnings()
  File "/usr/local/lib/python2.7/dist-packages/cpp/find_warnings.py", line 124, in find_warnings
    self._find_header_warnings()
  File "/usr/local/lib/python2.7/dist-packages/cpp/find_warnings.py", line 396, in _find_header_warnings
    self._find_unused_warnings()
  File "/usr/local/lib/python2.7/dist-packages/cpp/find_warnings.py", line 387, in _find_unused_warnings
    included_files, forward_declarations = self._read_and_parse_includes()
  File "/usr/local/lib/python2.7/dist-packages/cpp/find_warnings.py", line 171, in _read_and_parse_includes
    module = self._get_module(node)
  File "/usr/local/lib/python2.7/dist-packages/cpp/find_warnings.py", line 149, in _get_module
    [_f for _f in builder.generate() if _f])
  File "/usr/local/lib/python2.7/dist-packages/cpp/ast.py", line 698, in generate
    token = self._get_next_token()
  File "/usr/local/lib/python2.7/dist-packages/cpp/ast.py", line 916, in _get_next_token
    return next(self.tokens)
  File "/usr/local/lib/python2.7/dist-packages/cpp/tokenize.py", line 276, in get_tokens
    raise TokenError('unexpected token')
cpp.tokenize.TokenError: unexpected token

**Comment by r-e-d** [comment]
Cppclean can now parse all Ogre3d headers.
