### ISSUE TITLE
Crash  _get_template_end on boost/tr1/array.hpp

### ISSUE THREAD

**Issue by amai2012** [myint/cppclean#83]
Running cppclean on boost/tr1/array.hpp crashes
~~~
Processing boost/boost/tr1/array.hpp
Traceback (most recent call last):
  File "/usr/bin/cppclean", line 145, in <module>
    sys.exit(main())
  File "/usr/bin/cppclean", line 120, in main
    entire_ast = list([_f for _f in builder.generate() if _f])
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 668, in generate
    result = self._generate_one(token)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 692, in _generate_one
    return method()
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 1417, in handle_template
    templated_types)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 1520, in _get_class
    body = list(ast.generate())
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 668, in generate
    result = self._generate_one(token)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 757, in _generate_one
    return self._get_method(temp_tokens, 0, None, False)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 1125, in _get_method
    templated_types, body, self.namespace_stack)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 286, in __init__
    self.parameters = converter.to_parameters(parameters)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 595, in to_parameters
    add_parameter()
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 550, in add_parameter
    True)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 502, in declaration_to_parts
    parts, i + 1)
  File "/usr/lib/python2.7/site-packages/cpp/ast.py", line 387, in _get_template_end
    token = tokens[end]
IndexError: list index out of range
~~~
I am using boost 1.53 (http://www.boost.org/users/history/version_1_53_0.html)

**Comment by r-e-d** [comment]
Hello,

My last commit should fix this crash :)

**Comment by amai2012** [comment]
Fix confirmed :-)
