### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by falconair** [myint/cppclean#95]
Just ran cppclean on a c++11 code base (normally compiled with gcc 4.8 on linux as well as windows using VS 2013+.

I see  this stack trace:

```
Traceback (most recent call last):
  File "/usr/bin/cppclean", line 145, in <module>
    sys.exit(main())
  File "/usr/bin/cppclean", line 138, in main
    quiet=args.quiet):
  File "/usr/lib/python2.7/site-packages/cpp/find_warnings.py", line 565, in run
    hunter.find_warnings()
  File "/usr/lib/python2.7/site-packages/cpp/find_warnings.py", line 124, in find_warnings
    self._find_header_warnings()
  File "/usr/lib/python2.7/site-packages/cpp/find_warnings.py", line 437, in _find_header_warnings
    self._find_unused_warnings(included_files, forward_declarations)
  File "/usr/lib/python2.7/site-packages/cpp/find_warnings.py", line 413, in _find_unused_warnings
    forward_declarations)
  File "/usr/lib/python2.7/site-packages/cpp/find_warnings.py", line 401, in _determine_uses
    _add_declaration(node.name, node.namespace)
  File "/usr/lib/python2.7/site-packages/cpp/find_warnings.py", line 252, in _add_declaration
    name = '::'.join(names) + '::' + name
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Unfortunately I can't include the code which caused this error. Also, it doesn't actually tell me which line in the C++ file caused this so it could be any of 150+ lines.

**Comment by r-e-d** [comment]
Can you retry with the latest version ?
