### ISSUE TITLE
NoneType has no attribute split

### ISSUE THREAD

**Issue by odeits** [myint/cppclean#96]
cppclean version 0.9

```
Traceback (most recent call last):
  File "/usr/local/bin/cppclean", line 145, in <module>
    sys.exit(main())
  File "/usr/local/bin/cppclean", line 138, in main
    quiet=args.quiet):
  File "/usr/local/lib/python2.7/site-packages/cpp/static_data.py", line 117, in run
    _find_warnings(filename, lines, entire_ast, True) +
  File "/usr/local/lib/python2.7/site-packages/cpp/static_data.py", line 67, in _find_warnings
    find_static(node)
  File "/usr/local/lib/python2.7/site-packages/cpp/static_data.py", line 49, in find_static
    _find_warnings(filename, lines, body, False)
  File "/usr/local/lib/python2.7/site-packages/cpp/static_data.py", line 64, in _find_warnings
    print_warning(node)
  File "/usr/local/lib/python2.7/site-packages/cpp/static_data.py", line 31, in print_warning
    for name in node.name.split(','):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by odeits** [comment]
The piece of code that seems to cause the problem is

```cpp 
 struct Init {
    Init() { std::srand(static_cast<unsigned int>(std::time(0))); }
  } static init;
```

After applying a local fix to assist debugging this is the message i got
`static data 'NONE'`

Local fix for reference:

changed:
```python
for name in node.name.split(','):
```
to:
```python
        names =   node.name.split(',') if node.name is not None else ['NONE']
        for name in names:
```

**Comment by r-e-d** [comment]
This should be fixed by the last patches.
